# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'klesarev-github-io'


menu:
- {name: 'Все разделы', path: 'tags', url: 'index.html'}
- {name: 'Архив', path: 'menu', url: 'writing.html'}
- {name: 'Обо мне', path: 'menu', url: 'about.html'}
- {name: 'Контакты', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/klesarev'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:m1sterfinch@yandex.ru'}
# - {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Раньше...'
  previous_page: 'Позже...'

sharing_button_prompt: 'Поделиться записью'

related_posts: 'Так же по теме:'

post_date_prefix: 'Написано '
